apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: aaggny4xn-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aaggny4xn-nodejs 
  name: aaggny4xn-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: aaggny4xn-nodejs 
